name: kalkulatorsederhana
description: A new Flutter project.

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  math_expressions: ^2.1.0


dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_kalkulator.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logounesa.png
    - assets/bgmenu.jpg
    - assets/logo_kalkulator.png
